routes/web.php
<?php

Auth::routes();
Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index');

Route::get('product/add', 'ProductController@create');
Route::get('product/{product}/delete', [
    'as'   => 'product.delete',
    'uses' => 'ProductController@destroy',
]);
Route::resource('/product', 'ProductController');

/**
 * @param $key
 * @param string $direction
 * @return bool
 */
if (!function_exists('is_active_sorter')) {
    function is_active_sorter($key, $direction = 'ASC')
    {
        if (request('sortby') == $key && request('sortdir') == $direction) {
            return true;
        }

        return false;
    }
}

app/Catagory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Catagory extends Model
{
    protected $fillable = ['name', 'description', 'code'];
}

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = ['name', 'description', 'product_image', 'price'];

    public function getImageAttribute()
    {
        return $this->product_image;
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/CatagoryController.php
<?php

namespace App\Http\Controllers;

use App\Catagory;
use Illuminate\Http\Request;

class CatagoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Catagory  $catagory
     * @return \Illuminate\Http\Response
     */
    public function show(Catagory $catagory)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Catagory  $catagory
     * @return \Illuminate\Http\Response
     */
    public function edit(Catagory $catagory)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Catagory  $catagory
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Catagory $catagory)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Catagory  $catagory
     * @return \Illuminate\Http\Response
     */
    public function destroy(Catagory $catagory)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use App\Http\Requests;
use Illuminate\Http\Request;

/**
 * For GSDH -
 *
 * Class HomeController
 * @package App\Http\Controllers
 */
class HomeController extends Controller
{
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Products on our home page
        $sortBy = 'id';
        $sortDirection = 'ASC';

        if (request('sortby') || request('sortdir')) {
            $sortBy = request('sortby');
            $sortDirection = request('sortdir');
        }

        $products = Product::orderBy($sortBy, $sortDirection)->paginate(6);
        return view('home' , compact('products'));
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProductFormRequest;
use App\Product;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class ProductController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Products
        $sortBy = 'id';
        $sortDirection = 'ASC';

        if (request('sortby') || request('sortdir')) {
            $sortBy = request('sortby');
            $sortDirection = request('sortdir');
        }

        $products = Product::orderBy($sortBy, $sortDirection)->paginate(6);

        return view('product/index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('product/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductFormRequest $request)
    {
        $product = Product::create($request->all());
        alert()->success('Product has been added.');

        return redirect()->route('product.edit', $product->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return view('product/show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return view('product/edit', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(ProductFormRequest $request, Product $product)
    {
        $product->update($request->all());

        alert()->success('Product has been updated.');

        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        Product::destroy($id);

        alert()->success('Product has been deleted.');

        return redirect('/product');
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
  <div class="container" style="background-color: white;">

      <div class="clearfix">
          <br /><br />
          <div class="pull-left">
              <div class="lead" style="font-size: xx-large; font-family: 'Arial Black';">Produkte</div>
          </div>
          <br /><br /><br /><br /><br />
      </div>

      <table class="table table-bordered table-hover table-striped" style="border:none;">
          <tbody style="border: none;">
          @foreach($products as $product)
              <tr>
                  <td>
                      <a><img src="{{ asset('/images/'.$product->image) }}"></a>
                  </td>
                  <td>
                      <p class="card-header" style="font-size: xx-large">{{ $product->name }}<br /><br />
                      <p class="card-header" style="font-size: larger;">{{ $product->description }}

                      <div class="clearfix">
                          <br /><br />
                          <div class="input-group-btn" style="vertical-align: bottom; text-align: end;">
                              <!-- <a href="{-- route('product.edit', $product->id) }}" class="btn btn-primary">Edit</a> -->
                              <a href="{{ route('product.edit', $product->id) }}" class="btn btn-danger" style="border-top-right-radius: 0;border-bottom-right-radius: 0;">
                                  Mehr Erfahren
                              </a>
                          </div>
                      </div>
                  </td>

              </tr>
          @endforeach
          </tbody>
      </table>
  </div>

@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>GSDH</title>

  <!-- Fonts -->
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700" rel='stylesheet' type='text/css'>

  <!-- Styles -->
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-PmY9l28YgO4JwMKbTvgaS7XNZJ30MK9FAZjjzXtlqyZCqBY6X6bXIkM++IkyinN+" crossorigin="anonymous">
  <link rel="stylesheet" href="https://unpkg.com/summernote@0.8.11/dist/summernote.css">

  <style>
    body {
      font-family: 'Lato';
    }

    .fa-btn {
      margin-right: 6px;
    }
  </style>
</head>
<body id="app-layout" style="background-color: #dfdcd7ff;">
<nav class="navbar navbar-light" style="height: 90px; background-color: white;">
  <div class="container" style="margin-top: 20px;">

    <div class="navbar-header">

      <!-- Collapsed Hamburger -->
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <!-- Branding Image -->
      <a class="navbar-brand" href="{{ url('/') }}">
          <img src="{{ asset('/images/nav-logo.jpg') }}" style="margin-top: -20px;">
      </a>
    </div>

    <div class="collapse navbar-collapse" id="app-navbar-collapse">
      <!-- Left Side Of Navbar -->
      <ul class="nav navbar-nav">
      <!--
        <li><a href="{-- url('/') }}">Home</a></li>
        <li><a href="{-- url('/product') }}">Products</a></li>
      -->
      </ul>

      <!-- Right Side Of Navbar -->
      <ul class="nav navbar-nav navbar-right">
          <!-- Public Links -->
          <li><a href="{{ url('/') }}">HOME</a></li>
          <li><a href="{{ url('/login') }}">ÜBER UNS</a></li>
          <li><a href="{{ url('/product') }}">PRODUKTE</a></li>
          <li><a href="{{ url('/home') }}">REFERENZEN</a></li>
          <li><a href="{{ url('/') }}">KONTAKT</a></li>
        <!-- Authentication Links -->
        @if (Auth::guest())
          <!-- <li><a href="{-- url('/login') }}">Login</a></li> -->
          <li><a href="{{ url('/register') }}">Register</a></li>
        @else
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              {{ Auth::user()->name }} <span class="caret"></span>
            </a>

            <ul class="dropdown-menu" role="menu">
              <li>
                <a href="{{ route('logout') }}"
                   onclick="event.preventDefault();
                            document.getElementById('logout-form').submit();"
                >
                  Logout
                </a>

                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    {{ csrf_field() }}
                </form>
              </li>
            </ul>
          </li>
        @endif
      </ul>
    </div>
  </div>
</nav>

@yield('content')

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha256-3edrmyuQ0w65f8gfBsqowzjJe2iM6n0nKciPUp8y+7E=" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js" integrity="sha384-vhJnz1OVIdLktyixHY4Uk3OHEwdQqPppqYR8+5mjsauETgLOcEynD9oPHhhz18Nw" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-timeago/1.6.3/jquery.timeago.min.js"></script>
<script src="https://unpkg.com/summernote@0.8.11/dist/summernote.js"></script>
<script src="https://unpkg.com/sweetalert@2.1.2/dist/sweetalert.min.js"></script>
@include('sweet::alert')
<script>
  $(function() {
    window.App = {

      init: function() {
        this.timeago();
        this.summernote();
      },

      timeago: function() {
        $("time").timeago();
      },

      summernote: function() {
        $('textarea').summernote();
      }

    };

    App.init()
  });
</script>
@include('layouts.footer')
</body>
</html>

resources/views/layouts/footer.blade.php
<!-- Footer -->
<footer class="footer text-left" style="margin-top: 40px;">
    <div class="container" style="background-color: white; width: 100%;">
        <div class="row" style="width: 100%;">

            <!-- Footer Location -->
            <div class="col-lg-4 mb-5 mb-lg-0">
                <h4 class="text-uppercase mb-4">&copy; Eg Crustag 2014</h4>
                <p class="lead mb-0" style="font-size: small;">Impressum
                    <br />
                </p>
            </div>

            <!-- Footer Social Icons -->
            <div class="col-lg-4 mb-5 mb-lg-0" style="margin-left: 180px;">
                <img src="{{ asset('/images/kontakt-footer.gif') }}">
            </div>

            <!-- Footer About Text -->
            <div class="col-lg-4">

            </div>

        </div>
    </div>
</footer>

resources/views/product/create.blade.php
@extends('layouts.app')

@section('content')
  <div class="container" style="background-color: white;">

    <form method="POST" action="/product" enctype="multipart/form-data">

      <div class="clearfix">
          <br /><br /><br />
        <div class="pull-left">
          <div class="lead">
            <strong>Add New Produkt</strong>
          </div>
        </div>
        <div class="pull-right">
          <button type="submit" class="btn btn-success">Save</button>
          <a href="/product" class="btn btn-default">Back to list</a>
        </div>
      </div>
      <hr>

      @include('product.form')
    </form>

  </div>
@endsection

resources/views/product/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="container" style="background-color: white;">

        <form method="POST" action="/product/{{ $product->id }}">
            <div class="clearfix">
              <br /><br /><br />
            <div class="pull-left">
              <div class="lead">
                <strong>Edit product</strong>
                <small>{{ $product->name }}</small>
              </div>
            </div>

            <div class="pull-right">
              <button type="submit" class="btn btn-success">Save</button>
              <a href="/product" class="btn btn-default">Back to list</a>
            </div>
          </div>
          <hr>

          {!! method_field('PUT') !!}
          @include('product.form')
        </form>

    </div>
@endsection

resources/views/product/form.blade.php
{!! csrf_field() !!}

<div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">

  <label for="name" class="control-label">
    {{ trans('name') }}
  </label>

  <input type="text"
         name="name"
         id="name"
         value="{{ old('name', @$product->name) }}"
         placeholder="name"
         required
         class="form-control">

  @if ($errors->has('name'))
    <div class="help-block">
      {{ $errors->first('name') }}
    </div>
  @endif
</div>

<div class="form-group {{ $errors->has('product_image') ? 'has-error' : '' }}">
    <label for="product_image" class="control-label">
        {{ trans('product_image') }}
    </label>

    <input type="file"
           name="product_image"
           id="product_image"
           value="{{ old('product_image', @$product->image) }}"
           placeholder="product_image" class="form-control">

    @if ($errors->has('product_image'))
        <div class="help-block">
            {{ $errors->first('product_image') }}
        </div>
    @endif
</div>

<div class="form-group {{ $errors->has('price') ? 'has-error' : '' }}">

  <label for="price" class="control-label">
    {{ trans('price') }}
  </label>

  <input type="text"
         name="price"
         id="price"
         value="{{ old('price', @$product->price) }}"
         placeholder="price" class="form-control">

  @if ($errors->has('price'))
    <div class="help-block">
      {{ $errors->first('price') }}
    </div>
  @endif
</div>

<div class="form-group {{ $errors->has('description') ? 'has-error' : '' }}">

  <label for="content" class="control-label">
    {{ trans('description') }}
  </label>

      <textarea
          name="description"
          id="description"
          placeholder="description"
          required
          class="form-control">{{ old('description', @$product->description) }}</textarea>

  @if ($errors->has('description'))
    <div class="help-block">
      {{ $errors->first('description') }}
    </div>
  @endif
</div>

<div class="form-group">
  <button type="submit" class="btn btn-success">Save</button>
  <a href="/product" class="btn btn-default">Back to list</a>
</div>

resources/views/product/index.blade.php
@extends('layouts.app')

@section('content')
  <div class="container" style="background-color: white;">

    <div class="clearfix">
        <br /><br /><br />
      <div class="pull-left">
        <div class="lead">Produkte</div>
      </div>
      <div class="pull-right">
        <a href="/product/add" class="btn btn-success">Add new</a>
      </div>
    </div>

    <hr>

    <table class="table table-bordered table-hover table-striped">
      <thead>
      <tr>
        <th class="col-xs-1">
          ID
          <div class="pull-right">
            <a href="?sortby=id&sortdir=ASC"
               class="btn btn-xs {{ is_active_sorter('id', 'ASC') ? 'btn-primary' : 'btn-default' }}">
              <i class="fa fa-arrow-up"></i>
            </a>
            <a href="?sortby=id&sortdir=DESC"
               class="btn btn-xs {{ is_active_sorter('id', 'DESC') ? 'btn-primary' : 'btn-default' }}">
              <i class="fa fa-arrow-down"></i>
            </a>
          </div>
        </th>
        <th class="col-xs-3">
          Product Name
          <div class="pull-right">
            <a href="?sortby=title&sortdir=ASC"
               class="btn btn-xs {{ is_active_sorter('title', 'ASC') ? 'btn-primary' : 'btn-default' }}">
              <i class="fa fa-arrow-up"></i>
            </a>
            <a href="?sortby=title&sortdir=DESC"
               class="btn btn-xs {{ is_active_sorter('title', 'DESC') ? 'btn-primary' : 'btn-default' }}">
              <i class="fa fa-arrow-down"></i>
            </a>
          </div>
        </th>
        <th class="col-xs-3">
          Last modified
          <div class="pull-right">
            <a href="?sortby=updated_at&sortdir=ASC"
               class="btn btn-xs {{ is_active_sorter('updated_at', 'ASC') ? 'btn-primary' : 'btn-default' }}">
              <i class="fa fa-arrow-up"></i>
            </a>
            <a href="?sortby=updated_at&sortdir=DESC"
               class="btn btn-xs {{ is_active_sorter('updated_at', 'DESC') ? 'btn-primary' : 'btn-default' }}">
              <i class="fa fa-arrow-down"></i>
            </a>
          </div>
        </th>
        <th class="col-xs-2">
          Action
        </th>
      </tr>
      </thead>
      <tbody>
      @foreach($products as $product)
        <tr>
          <td>{{ $product->id }}</td>
          <td>
            <a href="/product/{{ $product->id }}">{{ $product->name }}</a>
          </td>
          <td>
            <time class="timeago" datetime="{{ $product->updated_at->toIso8601String() }}"
                  title="{{ $product->updated_at->toDayDateTimeString() }}">
              {{ $product->updated_at->diffForHumans() }}
            </time>
          </td>
          <td>
            <div class="input-group-btn">
              <a href="{{ route('product.edit', $product->id) }}" class="btn btn-primary">Edit</a>
              <a href="{{ route('product.delete', $product->id) }}" class="btn btn-danger"
                 onclick="return confirm('Are you sure to delete this product ?');">
                Delete
              </a>
            </div>
          </td>
        </tr>
      @endforeach
      </tbody>
    </table>

    <div class="text-center">
      {!! $products->appends(request()->except('product'))->links() !!}
    </div>

  </div>
@endsection

resources/views/product/show.blade.php
@extends('layouts.app')

@section('content')

  <div class="container" style="background-color: white;">

    <h2>{{ $product->name }}</h2>

    <div>
      Posted by {{ $product->name }}
      <time class="timeago" datetime="{{ $product->updated_at->toIso8601String() }}"
            title="{{ $product->updated_at->toDayDateTimeString() }}">
        {{ $product->updated_at->diffForHumans() }}
      </time>
    </div>

    <hr>

    <div>
      {!! $product->descrition !!}
    </div>

  </div>

@endsection